import type { Suite } from "@/interface/suites";

// Sample data for testing
export const suitesData: Suite[] = [
  {
    id: "1",
    name: "Forest View King",
    description:
      "A luxurious king suite with stunning forest views and premium amenities.",
    max_guests: 4,
    regular_price: 450.0,
    discount: 50.0,
    features: {
      wifi: true,
      airConditioning: true,
      tv: true,
      petFriendly: false,
      freeBreakfast: true,
      privateBalcony: true,
      jacuzzi: false,
      oceanView: false,
      butlerService: false,
      roomService: true,
      miniBar: true,
      inRoomSafe: true,
      smartLighting: false,
      soundProofing: true,
      heatedFloors: false,
    },
    images: ["/placeholder.svg?height=64&width=64"],
    is_available: true,
    created_at: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "Lakeside Queen",
    description:
      "Peaceful queen suite overlooking the serene lake with modern comforts.",
    max_guests: 2,
    regular_price: 320.0,
    discount: 0,
    features: {
      wifi: true,
      airConditioning: true,
      tv: true,
      petFriendly: true,
      freeBreakfast: false,
      privateBalcony: true,
      jacuzzi: false,
      oceanView: false,
      butlerService: false,
      roomService: false,
      miniBar: false,
      inRoomSafe: true,
      smartLighting: true,
      soundProofing: false,
      heatedFloors: false,
    },
    images: ["/placeholder.svg?height=64&width=64"],
    is_available: false,
    created_at: "2024-01-10T14:20:00Z",
  },
  {
    id: "3",
    name: "Mountain Vista Suite",
    description:
      "Spacious suite with breathtaking mountain views and luxury amenities for families.",
    max_guests: 6,
    regular_price: 680.0,
    discount: 100.0,
    features: {
      wifi: true,
      airConditioning: true,
      tv: true,
      petFriendly: true,
      freeBreakfast: true,
      privateBalcony: true,
      jacuzzi: true,
      oceanView: false,
      butlerService: true,
      roomService: true,
      miniBar: true,
      inRoomSafe: true,
      smartLighting: true,
      soundProofing: true,
      heatedFloors: true,
    },
    images: ["/placeholder.svg?height=64&width=64"],
    is_available: true,
    created_at: "2024-01-05T09:15:00Z",
  },
  {
    id: "4",
    name: "Garden Terrace Double",
    description:
      "Cozy double room with access to beautiful garden terrace and peaceful atmosphere.",
    max_guests: 2,
    regular_price: 280.0,
    discount: 0,
    features: {
      wifi: true,
      airConditioning: false,
      tv: true,
      petFriendly: false,
      freeBreakfast: true,
      privateBalcony: false,
      jacuzzi: false,
      oceanView: false,
      butlerService: false,
      roomService: false,
      miniBar: false,
      inRoomSafe: false,
      smartLighting: false,
      soundProofing: false,
      heatedFloors: false,
    },
    images: ["/placeholder.svg?height=64&width=64"],
    is_available: true,
    created_at: "2024-01-20T16:45:00Z",
  },
  {
    id: "5",
    name: "Riverside Deluxe",
    description:
      "Deluxe suite with riverside views and premium services for a memorable stay.",
    max_guests: 4,
    regular_price: 520.0,
    discount: 75.0,
    features: {
      wifi: true,
      airConditioning: true,
      tv: true,
      petFriendly: false,
      freeBreakfast: true,
      privateBalcony: true,
      jacuzzi: true,
      oceanView: false,
      butlerService: false,
      roomService: true,
      miniBar: true,
      inRoomSafe: true,
      smartLighting: true,
      soundProofing: true,
      heatedFloors: false,
    },
    images: ["/placeholder.svg?height=64&width=64"],
    is_available: false,
    created_at: "2024-01-12T11:30:00Z",
  },
];
